[workspace]
resolver = "2"
members = [
    "crates/onetagger",
    "crates/onetagger-cli",
    "crates/onetagger-tag",
    "crates/onetagger-shared",
    "crates/onetagger-player",
    "crates/onetagger-tagger",
    "crates/onetagger-python",
    "crates/onetagger-renamer",
    "crates/onetagger-autotag",
    "crates/onetagger-playlist",
    "crates/onetagger-platforms",
    "crates/onetagger-python-builder",
]

# Optimize for size
[profile.release]
opt-level = 3
strip = true
