[package]
name = "onetagger"
version = "1.0.0"
authors = ["Marekkon5"]
edition = "2018"
license = "Apache"
description = "App to tag your music library."
keywords = ["gui", "audio"]
categories = ["multimedia::audio"]
build = "src/build.rs"

[dependencies]
app_dirs = "1.2"
tempfile = "3.2"
rodio = "0.13"
mp3-duration = "0.1.10"
slog-term = "2.8"
slog = "2.7"
slog-scope = "4.4"
tinyfiledialogs = "3.3.10"
rouille = "3.0"
tungstenite = "0.13"
web-view = "0.7.3"
minify-html = "0.4"
walkdir = "2.3"
threadpool = "1.8"
strsim = "0.10"
regex = "1"
scraper = "0.12"
serde_json = "1.0"
id3 = "0.6.2"
metaflac = "0.2.4"
chrono = "0.4"
webbrowser = "0.5"
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1.0", features = ["derive"] }
rspotify = { git = "https://github.com/ramsayleung/rspotify.git", features = ["client-ureq", "ureq-rustls-tls"], default-features = false }
ffmpeg-decoder = { git = "https://github.com/Marekkon5/ffmpeg-decoder-rs.git", features = ["rodio_source"] }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser", "libloaderapi"] }
cef = { git = "https://github.com/Marekkon5/cef.git" }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

# Optimize for size
[profile.release]
opt-level = 'z'

[package.metadata.bundle]
name = "OneTagger"
identifier = "com.marekkon5.onetagger"
icon = ["assets/32x32.png", "assets/128x128.png", "assets/128x128@2x.png", "assets/icon.icns", "assets/icon.ico"]
version = "1.0.0"
resources = []
copyright = "Copyright (c) Marekkon5 2021. All rights reserved."
category = "Music"
short_description = "Tool to tag your audio library."
long_description = """
Tool to tag your audio library.
"""