[workspace]
members = [
    "crates/onetagger",
    "crates/onetagger-cli",
    "crates/onetagger-tag",
    "crates/onetagger-shared",
    "crates/onetagger-player",
    "crates/onetagger-tagger",
    "crates/onetagger-renamer",
    "crates/onetagger-autotag",
    "crates/onetagger-playlist",
    "crates/onetagger-platforms",
]

# Optimize for size
[profile.release]
opt-level = 3
strip = true