# Mac OS libraries
[target.x86_64-apple-darwin]
rustflags = ["-lz", "-lbz2", "-llzma", "-C", "link-args=-framework AudioUnit"]

# Windows static build
[target.stable-x86_64-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]
