[package]
name = "onetagger-player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mp4 = "0.13"
alac = "0.5"
hound = "3.5"
rodio = "0.16"
lofty = "0.11"
redlux = "0.6"
mp3-duration = "0.1"

onetagger-shared = { path = "../onetagger-shared" }

# Outdated ndarray for sndfile
ndarray = { version = "0.13", optional = true }
sndfile = { version = "0.1.1", features = ["ndarray_features"], optional = true }


[features]
default = ["aiff"]
aiff = ["ndarray", "sndfile"]