[package]
name = "onetagger-player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mp4 = "0.13"
alac = "0.5"
hound = "3.5"
rodio = "0.16"
lofty = "0.11"
redlux = "0.6"
mp3-duration = "0.1"

onetagger-shared = { path = "../onetagger-shared" }


# https://github.com/AkiyukiOkayasu/pacmog/pull/28
pacmog = { git = "https://github.com/Marekkon5/pacmog.git", branch = "remove_assert" }
