[package]
name = "onetagger-python-builder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.6"
ureq = "2.7"
regex = "1.9"
anyhow = "1.0"
walkdir = "2.3"
pyoxidizer = "0.24"