name: Build
on: [push, pull_request]

jobs:
  build-linux:
    name: Linux + Mac
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libasound2-dev pkg-config make yasm libssl-dev libxml2-dev cmake clang gcc g++ zlib1g-dev libmpc-dev libmpfr-dev libgmp-dev curl wget git python2 libwebkit2gtk-4.0-dev

    - name: Build ffmpeg
      run: |
        wget https://ffmpeg.org/releases/ffmpeg-4.3.2.tar.gz
        tar zxf ffmpeg-4.3.2.tar.gz
        cd ffmpeg-4.3.2
        ./configure --disable-shared --enable-static --disable-programs --disable-doc
        make -j8
        sudo make install
        cd ..

    - name: Run build script
      run: |
        chmod +x assets/compile-nix.sh
        ./assets/compile-nix.sh
    
    - name: Upload Linux
      uses: actions/upload-artifact@v2
      with:
        name: onetagger-linux
        path: dist/OneTagger-linux

    - name: Upload Mac
      uses: actions/upload-artifact@v2
      with:
        name: onetagger-mac
        path: dist/OneTagger-mac.zip

  build-win:
    name: Windows
    runs-on: windows-latest
    
    steps:
      
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install Dependencies
      run: |
        choco install nsis 7zip -y
    
    # Required for bindgen to work, see https://github.com/rust-lang/rust-bindgen/issues/1797
    - name: Install LLVM and Clang 
      uses: KyleMayes/install-llvm-action@v1.2.1
      with:
        version: "11.0"
        directory: ${{ runner.temp }}/llvm
    - name: Set LIBCLANG_PATH
      run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV

    - name: Run build script
      run: |
        python assets/compile-win.py
    
    - name: Upload Archive
      uses: actions/upload-artifact@v2
      with:
        name: onetagger-win
        path: dist/OneTagger-windows.7z
    
    - name: Upload Archive
      uses: actions/upload-artifact@v2
      with:
        name: onetagger-win-setup
        path: dist/OneTagger-windows.exe
      