name: Build
on: [push, pull_request]

jobs:
  build-linux:
    name: Linux + Mac
    runs-on: ubuntu-18.04

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y autogen libsndfile1-dev libasound2-dev pkg-config make libssl-dev gcc g++ curl wget git libwebkit2gtk-4.0-dev

    - name: Run build script
      run: |
        chmod +x assets/compile-nix.sh
        ./assets/compile-nix.sh
    
    - name: Upload Linux
      uses: actions/upload-artifact@v2
      with:
        name: onetagger-linux
        path: dist/OneTagger-linux.tar.gz

    - name: Upload Mac
      uses: actions/upload-artifact@v2
      with:
        name: onetagger-mac
        path: dist/OneTagger-mac.zip

  build-win:
    name: Windows
    runs-on: windows-latest
    
    steps:
      
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install Dependencies
      run: |
        choco install nsis -y

    - name: Build
      run: |
        cd client
        npm i
        npm run build
        cd ..
        copy assets\sndfile.lib .
        cargo build --release
        
    - name: Bundle
      run: |
        mkdir dist
        powershell -command "(new-object System.Net.WebClient).DownloadFile('https://aka.ms/vs/16/release/vc_redist.x64.exe','vc_redist.x64.exe')"
        "C:\Program Files (x86)\NSIS\makensis.exe" assets\installer.nsi
        copy target\release\onetagger.exe dist\OneTagger-windows.exe

    - name: Upload Archive
      uses: actions/upload-artifact@v2
      with:
        name: onetagger-win
        path: dist/OneTagger-windows.exe
    
    - name: Upload Archive
      uses: actions/upload-artifact@v2
      with:
        name: onetagger-win-setup
        path: dist/OneTagger-windows-setup.exe
      